title: Juan D Chacon # your name (or website title) here
logo: "/images/juanChacon.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A data scientist with a passion for real-world practice. I seek to work in an environment that will challenge me further while allowing me to contribute to the continued growth and success of organizations.
  <br><br>
Work Experience Summary

Training, Evaluating, Testing & Deploying Data-Driven Models (Scikit-learn, Spark MLlib, TensorFlow)
Data Mining, Aggregating & Presenting using tools like Pandas, Spark, SQL, & Tableau
Developing pipelines to ETL data from both real-time and static data sources using PySpark
Developing dockerized web services using Django, Flask using the TDD paradigm
  <br><br> 
Work Experience Detail
 
Aug 2018  to  Aug 2020 (Part-time) Research Assistant 	At Simon Fraser University - Burnaby, BC
Propose a control framework for multivehicle coverage of domains by swarms of drones or plane-aircrafts.
Simulate the agent’s dynamics for different scenarios and document results.
  <br><br>
Apr 2018 to Aug 2018 Data Scientist, Machine Learning Engineer	At Portal Finance - Bogotá, COL 
Work closely with Risk experts to develop models for factoring operations using little data.
Develop APIs for risk estimations as a service, working with DevOps and software engineers for the deployment of Dockerized web services.
Extract features from raw data for the risk models.
  <br><br>
Aug 2017 to Mar 2018 Data Scientist, Machine Learning Engineer 	At Fluvip - Bogotá, COL
Develop and deploy estimation models for social media engagement statistics from historic data.
Estimate sample sizes for confidence intervals for statistical estimators.
Collect data from APIs or Web scraping.
  <br><br>
Feb 2016 to May 2017 Research Assistant 	At Centro internacional de Fisica - Bogotá, COL
I refocused a project with serious delays, obtaining good results from the second month.
Propose machine learning and statistical inference models for landmine detection using thermal neutron backscattering.
Develop a neutron data collection spectroscopy device based on a fast pulse counter and discriminator using a microcontroller.
  <br><br>
Oct 2015 to Jan 2016 Research Assistant 	At CIRMAG - Bogotá, COL
Train linear and nonlinear regression models for the forecast of the Magdalena river levels
Establish imputation strategies for missing data.
 
  <br><br>
Education
Aug 2020    MSc. Applied Mathematics, Simon Fraser University (With Distinction) 	(GPA 4.18 / 4.33)
Mar 2016    MSc. Mathematics, Universidad Nacional De Colombia	(GPA 4.8 / 5.0)
Jun 2017    BEng. Electronics, Universidad Distrital FJDC 	(GPA 4.0 / 5.0)
Mar 2013    BSc. Mathematics, Universidad Nacional De Colombia 	(GPA 4.2 / 5.0)
  <br><br>
  <a href="https://www.linkedin.com/in/juan-d-chacon-a7a914a2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
